services:
  - type: web
    name: glido-backend
    runtime: node
    repo: https://github.com/Atofinite5/Glido.ai-Project
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://frontend-eosin-psi-96.vercel.app
      - key: PORT
        value: "10000"
